# Generated by Django 5.1 on 2024-08-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, max_length=15, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
