# Generated by Django 5.1 on 2024-08-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_contactos_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='contactos'),
        ),
    ]
